config/routes.rb
Gfistainless::Application.routes.draw do

  namespace(:admin){ resources :manufacturers }

  get "products" => "products#index", as: "products"
  get "products/show/*id" => "products#show", as: "productcat"
  get "products/display/*id" => "products#display", as:"product"
  

  Mercury::Engine.routes

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :pages do
    member { post :mercury_update }
  end
  namespace :admin do
    resources :productcategories
    resources :products
  end

  root :to => 'home#index'

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :products
  validates :name, presence: true, length: {maximum:250}
  validates :url, length: {maximum:250}
end

app/controllers/admin/manufacturers_controller.rb
class Admin::ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(params[:manufacturer])
    if @manufacturer.save
      redirect_to [:admin, @manufacturer], :notice => "Successfully created manufacturer."
    else
      render :action => 'new'
    end
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])
    if @manufacturer.update_attributes(params[:manufacturer])
      redirect_to [:admin, @manufacturer], :notice  => "Successfully updated manufacturer."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy
    redirect_to admin_manufacturers_url, :notice => "Successfully destroyed manufacturer."
  end
end

app/helpers/admin/manufacturers_helper.rb
module Admin::ManufacturersHelper
end

app/views/admin/manufacturers/_form.html.erb
<%= form_for [:admin, @manufacturer] do |f| %>

	<% if @manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/admin/manufacturers/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @manufacturer] %> |
  <%= link_to "View All", admin_manufacturers_path %>
</p>

app/views/admin/manufacturers/index.html.erb
<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for manufacturer in @manufacturers %>
    <tr>
      <td><%= manufacturer.name %></td>
      <td><%= link_to "Show", [:admin, manufacturer] %></td>
      <td><%= link_to "Edit", edit_admin_manufacturer_path(manufacturer) %></td>
      <td><%= link_to "Destroy", [:admin, manufacturer], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/Manufacturer", new_admin_manufacturer_path %></p>

app/views/admin/manufacturers/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", admin_manufacturers_path %></p>

app/views/admin/manufacturers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @manufacturer.name %>
</p>

<p>
  <%= link_to "Edit", edit_admin_manufacturer_path(@manufacturer) %> |
  <%= link_to "Destroy", [:admin, @manufacturer], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_manufacturers_path %>
</p>