config/routes.rb
Gfistainless::Application.routes.draw do

  namespace(:admin){ resources :manufacturers }

  get "products" => "products#index", as: "products"
  get "products/show/*id" => "products#show", as: "productcat"
  get "products/display/*id" => "products#display", as:"product"
  

  Mercury::Engine.routes

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :pages do
    member { post :mercury_update }
  end
  namespace :admin do
    resources :productcategories
    resources :products
  end

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :productcategory
  belongs_to :manufacturer
  
  validates :name, presence: true, length: {maximum:250}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @productcategories = Productcategory.order(:names_depth_cache).map { |c| ["-" * c.depth + c.name,c.id] }
    @manufacturers = Manufacturer.order(:name).map { |m| [m.name, m.id]}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @productcategories = Productcategory.order(:names_depth_cache).map { |c| ["-" * c.depth + c.name,c.id] }
    @manufacturers = Manufacturer.order(:name).map { |m| [m.name, m.id]}
  end

  # POST /products
  # POST /products.json
  def create
    #@product = Product.new(params[:product])
    @product=Product.new(params[:product])
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin,@product], notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: [:admin,@product] }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
     
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to [:admin,@product], notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :ok }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories=Productcategory.scoped
  end
  
  def show
    @category=Productcategory.find(params[:id])
    
    @category_ancestors=@category.ancestors
    @category_children=@category.children.scoped
    @products=Product.where(productcategory_id: @category.subtree_ids)
  end
  
  def display
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin,@product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :productcategory %><br />
    <%= f.select :productcategory_id, @productcategories %>
  </div>
	<div class="field">
		<%= f.label :manufacturer%>
		<%= f.select :manufacturer_id, @manufacturers%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@product] %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.productcategory.name %></td>
    <td><%= link_to 'Show', admin_product_path(product) %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(product)  %></td>
    <td><%= link_to 'Destroy', admin_products_path, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Category:</b>
  <%= @product.productcategory.name %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>