config/routes.rb
Gfistainless::Application.routes.draw do

  namespace(:admin){ resources :manufacturers }

  get "products" => "products#index", as: "products"
  get "products/show/*id" => "products#show", as: "productcat"
  get "products/display/*id" => "products#display", as:"product"
  

  Mercury::Engine.routes

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :pages do
    member { post :mercury_update }
  end
  namespace :admin do
    resources :productcategories
    resources :products
  end

  root :to => 'home#index'

end

app/models/productcategory.rb
class Productcategory < ActiveRecord::Base
  has_ancestry
  before_save :cache_ancestry
  
  validates :name, presence: true, length: {maximum:250}

  def cache_ancestry
    self.names_depth_cache = path.map(&:name).join('/')
  end
  
end

app/controllers/admin/productcategories_controller.rb
class Admin::ProductcategoriesController < ApplicationController
  # GET /productcategories
  # GET /productcategories.json
  def index
    @productcategories = Productcategory.scoped
    #@productcategory = Productcategory.new

   
  end

  # GET /productcategories/1
  # GET /productcategories/1.json
  def show
    @productcategory = Productcategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @productcategory }
    end
  end

  # GET /productcategories/new
  # GET /productcategories/new.json
  def new()
    @productcategory = Productcategory.new(parent_id: params[:parent_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @productcategory }
    end
  end

  # GET /productcategories/1/edit
  def edit
    @productcategory = Productcategory.find(params[:id])
  end

  # POST /productcategories
  # POST /productcategories.json
  def create
    @productcategory = Productcategory.new(params[:productcategory])
    if @productcategory.ancestry ==""
      @productcategory.ancestry = nil
    end
    respond_to do |format|
      if @productcategory.save
        format.html { redirect_to [:admin,@productcategory], notice: 'Productcategory was successfully created.' }
        format.json { render json: @productcategory, status: :created, location: [:admin,@productcategory] }
      else
        format.html { render action: "new" }
        format.json { render json: @productcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productcategories/1
  # PUT /productcategories/1.json
  def update
    @productcategory = Productcategory.find(params[:id])

    respond_to do |format|
      if @productcategory.update_attributes(params[:productcategory])
        format.html { redirect_to [:admin,@productcategory], notice: 'Productcategory was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @productcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productcategories/1
  # DELETE /productcategories/1.json
  def destroy
    @productcategory = Productcategory.find(params[:id])
    @productcategory.destroy

    respond_to do |format|
      format.html { redirect_to admin_productcategories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/productcategories_helper.rb
module ProductcategoriesHelper
  
end

app/views/admin/productcategories/_form.html.erb
<%= form_for([:admin,@productcategory]) do |f| %>
  <% if @productcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@productcategory.errors.count, "error") %> prohibited this productcategory from being saved:</h2>

      <ul>
      <% @productcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.text_field :name%>
	<%= f.hidden_field :parent_id%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/productcategories/_productcategory.html.erb
<div class="productcategory">
	<div class="content">
		<%= link_to productcategory.name, admin_productcategory_path(productcategory) %>
	</div>
</div>

app/views/admin/productcategories/edit.html.erb
<h1>Editing productcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @productcategory] %> |
<%= link_to 'Back', admin_productcategories_path %>

app/views/admin/productcategories/index.html.erb
<h1>Listing productcategories</h1>

<%= nested_categories @productcategories.arrange(:order=>:name),'admin/productcategories/productcategory', 'nested_categories' %>
<%= link_to 'New Productcategory', new_admin_productcategory_path %>

app/views/admin/productcategories/new.html.erb
<h1>New productcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_productcategories_path %>

app/views/admin/productcategories/show.html.erb
<p id="notice"><%= notice %></p>

<%= nested_categories @productcategory.subtree.arrange(order: :name)%>

<%= link_to 'Create Sub Category', new_admin_productcategory_path(parent_id: @productcategory.id)%>

<%= link_to 'Edit', edit_admin_productcategory_path(@productcategory) %> |
<%= link_to 'Back', admin_productcategories_path %>